//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcFirmaCagri.Models.entity
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DbisTakipEntities : DbContext
    {
        public DbisTakipEntities()
            : base("name=DbisTakipEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<TBLAdmin> TBLAdmin { get; set; }
        public virtual DbSet<TBLCagrilar> TBLCagrilar { get; set; }
        public virtual DbSet<TBLdepartmanlar> TBLdepartmanlar { get; set; }
        public virtual DbSet<TBLFirmalar> TBLFirmalar { get; set; }
        public virtual DbSet<TBLGorevDetaylar> TBLGorevDetaylar { get; set; }
        public virtual DbSet<TBLGorevler> TBLGorevler { get; set; }
        public virtual DbSet<TBLPersonel> TBLPersonel { get; set; }
    }
}
