//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcFirmaCagri.Models.entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBLGorevler
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TBLGorevler()
        {
            this.TBLGorevDetaylar = new HashSet<TBLGorevDetaylar>();
        }
    
        public int ID { get; set; }
        public Nullable<int> Gorev_Veren { get; set; }
        public Nullable<int> GorevAlan { get; set; }
        public string Aciklama { get; set; }
        public Nullable<bool> Durum { get; set; }
        public Nullable<System.DateTime> Tarih { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBLGorevDetaylar> TBLGorevDetaylar { get; set; }
        public virtual TBLPersonel TBLPersonel { get; set; }
        public virtual TBLPersonel TBLPersonel1 { get; set; }
    }
}
